feat: disable sponsorblock on shorts
revanced/revanced-integrations pull request #135
Opened 2022-09-07 22:31 UTC by OxrxL

2022-09-14 14:16 UTC, oSumAtrIX requested changes

2022-09-14 14:16 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
> +    public static boolean SB_SHORTS_ENABLED = false;
Make sure to also adjust this in the [related patch](https://github.com/revanced/revanced-patches/pull/439).

```suggestion
    public static boolean shorts_playing = false;
```

2022-09-14 18:19 UTC, OxrxL commented
> There are a lot of changes, that were not necessary. The `sponsorblock` patch only injects couple of calls to methods into the application, only these methods should be blocked.

I need to know which are these methods, otherwise it will become quite difficult for me to find out

2022-09-15 00:53 UTC, oSumAtrIX commented
Sure, all calls to the methods in the integrations can be found [here](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch/SponsorBlockBytecodePatch.kt). Simply `CTRL+F` and search for `integrations/` to get a good understanding.

2022-09-15 00:57 UTC, OxrxL commented
> Sure, all calls to the methods in the integrations can be found [here](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch/SponsorBlockBytecodePatch.kt). Simply `CTRL+F` and search for `integrations/` to get a good understanding.

At first look I should find an unused register for each call. It does not make the operation more complex?

2022-09-15 01:03 UTC, OxrxL commented
> Sure, all calls to the methods in the integrations can be found [here](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch/SponsorBlockBytecodePatch.kt). Simply `CTRL+F` and search for `integrations/` to get a good understanding.

Nevermind. I said nonsense. You were referring to the changes to be made to the integrations and not to the patch. xD

2022-09-15 01:09 UTC, oSumAtrIX commented
No problem, yeah, simply add the condition in the integrations methods instead of patching the application.

2022-09-15 01:55 UTC, OxrxL commented
Should be good now. For safeness, test it you too. :D

2022-09-20 23:47 UTC, oSumAtrIX requested changes

2022-09-20 23:47 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockUtils.java
> +        if (SettingsEnum.shorts_playing) return "";
Should this not be:
```suggestion
        if (SettingsEnum.shorts_playing) return totalTime;
```
?

2022-09-21 01:03 UTC, oSumAtrIX approved these changes

2022-09-21 01:03 UTC, merged