feat(tiktok): `fiktok-feed-filter` patch
revanced/revanced-integrations pull request #142
Opened 2022-09-16 11:04 UTC by d4rkk3y

2022-09-16 23:49 UTC, oSumAtrIX commented
Soon, every patch will have their own integrations. General integrations like this will also still exist providing basic utility methods like settings or methods to the Android API (which the patch integrations will not have access to), but patch specific code will be moved to the patches own integrations. The current problem with this PR is that using this integrations in other applications will still merge the integrations code for TikTok patches. Would it be possible to make this repository build separate integrations, in this case, one for TikTok and the other for YouTube? This way, we can then easily migrate to patch specific integrations and prevent unrelated code from getting merged.

2022-09-17 00:38 UTC, Sculas commented
@oSumAtrIX I think that the way this PR is, is okay for now. It's better to just have it be "wrong" and then fix it later than doing a half-assed implementation and having to fix it later anyway. But it's up to you.

2022-09-17 01:07 UTC, oSumAtrIX commented
Actually, merging unrelated code is more of a half assed implementation then creating a proper solution which would be integrations specifically made for each patch, or until thats done, for these patches for now. This way, useless code would be prevented to be merged to our current apps and the same for the app @d4rkk3y patches. The solution is simply to create a separate integrations apk. Then either you use the current integrations or the new ones specifically for these patches.

2022-09-17 01:27 UTC, Sculas commented
That'd require a whole new repository and new IntegrationsPatch dependency for.. just this? And for it then all be removed when everything is refactored into how you said it would be like? Don't think only about yourself if that's what you do, think about the author too who has to do all of that with no added value.

2022-09-17 05:04 UTC, d4rkk3y commented
@oSumAtrIX @Sculas I have a idea. How about create a annotation to mark a class in integration belong to target app? And then implement merge method in `patcher` which will check it and merge if current patching app is target app.

2022-09-18 14:16 UTC, oSumAtrIX commented
> That'd require a whole new repository and new IntegrationsPatch dependency for.. just this? And for it then all be removed when everything is refactored into how you said it would be like? Don't think only about yourself if that's what you do, think about the author too who has to do all of that with.
> 
> Instead, if you insist on going with this route, merge this PR and make that huge change yourself or ask if the author would like to do that. Either way, you'll have to help because you need to make a repository for it.

No, that's not required, it can be done in this repo pretty straight forward. Less refactoring will happen if the integrations are being started to be separated now for each app.

2022-09-20 23:40 UTC, E85Addict commented
I've tested both this and [#501](https://github.com/revanced/revanced-patches/pull/501) together and it seems to work flawless, is there anything left that is required in the PR's before merge?

2022-09-21 00:02 UTC, oSumAtrIX commented
> @oSumAtrIX @Sculas I have a idea. How about create a annotation to mark a class in integration belong to target app? And then implement merge method in `patcher` which will check it and merge if current patching app is target app.

This would require to annotate all classes which should be merged, including those which are shaded into the integrations to which an annotation can not be added. As an alternative every class which does not have this particular annotation, could be merged by default, while those who have, but do not match the selected app, are excluded. For the scope of this PR it is better to separate this to another PR, please revert the intruduction of the `MergeIf` annotation so we can merge this PR for now.

2022-09-21 00:05 UTC, oSumAtrIX requested changes

2022-09-21 00:05 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/tiktok/settings/SettingsEnum.java
> +import merger.MergeIf;
```suggestion
```

2022-09-21 00:05 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/tiktok/settings/ReturnType.java
> +import merger.MergeIf;
```suggestion
```

2022-09-21 00:05 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/tiktok/feedfilter/FeedItemsFilter.java
> +import merger.MergeIf;
```suggestion
```

2022-09-21 00:05 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/tiktok/MergeIfPackage.java
> +}
Remove this file.

2022-09-21 00:05 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/MergeIfPackage.java
> +}
Remove this file.

2022-09-21 20:31 UTC, E85Addict commented
Tested the corrections all is working!

2022-09-21 20:57 UTC, oSumAtrIX approved these changes

2022-09-21 20:59 UTC, merged