fix(theme): generalize comments filter bar patch
revanced/revanced-integrations pull request #176
Opened 2022-10-14 21:28 UTC by OxrxL

2022-10-14 23:04 UTC, oSumAtrIX commented
Does this implementation consider theming the light mode theme?

2022-10-14 23:05 UTC, OxrxL commented
> Does this implementation consider theming the light mode theme?

Already included inside integration java class.

2022-10-14 23:06 UTC, OxrxL commented on app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
> +        if (!ThemeHelper.isDarkTheme()) {
This is what you're looking for @oSumAtrIX

2022-10-14 23:07 UTC, oSumAtrIX commented
The current implementation is a bit unclear, please give the parameters and variables more explanatory names as well as comment your code to explain what it does for future reference.

2022-10-14 23:11 UTC, OxrxL commented
> The current implementation is a bit unclear, please give the parameters and variables more explanatory names as well as comment your code to explain what it does for future reference.

Do the same thing of the hard codes patch:

Really easy:

This method check if the theme is white or dark and, based on this condition, isolates (with another condition) the individual color values from the register field p1, to subsequently change them to zero (transparent color) and hide the panel elements drawn by litho.

2022-10-14 23:12 UTC, oSumAtrIX commented
> with another condition

This is unclear, please refactor the code as mentioned.

2022-10-14 23:13 UTC, OxrxL commented
> > with another condition
> 
> This is unclear, please refactor the code as mentioned.

Are you blind? I already added the check for light theme. 🤷‍♂️

2022-10-14 23:16 UTC, oSumAtrIX commented
I asked to refactor the code by properly naming your variables and parameters, not change the behavior.

2022-10-14 23:17 UTC, OxrxL commented
> I asked to refactor the code by properly naming your variables and parameters, not change the behavior.

Yeah...sorry. There was a misunderstanding by me.

2022-10-20 20:11 UTC, oSumAtrIX requested changes

2022-10-20 20:11 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
> +    private static final int[] DARKCONSTANTS = {
```suggestion

    private static final int[] DARKCONSTANTS = {
```

2022-10-20 20:16 UTC, oSumAtrIX requested changes

2022-10-20 20:16 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
> +    }
```suggestion
    public static int applyLithoTheme(int originalValue) {
        var isDarkTheme = ThemeHelper.isDarkTheme();
        
        if ((isDarkTheme  && anyEquals(originalValue, DARKCONSTANTS)) || (!isDarkTheme  && anyEquals(originalValue, WHITECONSTANTS)))
                return 0;
        return originalValue;
    }
```

2022-10-25 07:56 UTC, merged