ReturnYouTubeDislike connection statistics. Show client toast messages on RYD connection errors.  High priority background threads.
revanced/revanced-integrations pull request #236
Opened 2022-12-12 19:09 UTC by LisoUseInAIKyrios

I changed the background thread pool so all threads run at max priority.

This change seems to reduce the average time needed to load the video UI, as the RYD vote fetch now gets priority over other background threads (the fetch is blocking the UI, it definitely should get priority). 

Currently this thread pool is only used by RYD for the fetch votes calls.

2022-12-12 19:10 UTC, oSumAtrIX commented
Can you include benchmark results

2022-12-12 20:45 UTC, LisoUseInAIKyrios commented
Benchmarking is not precise since it's affected by whatever is going on in the background, how fast YouTube responds for each video, internet connection speed at that moment, etc, etc, etc.

Without patch.  Loading 20 random videos:

```
revanced: ReturnYouTubeDislike: UI thread paused for: 1071ms waiting for vote fetch to complete
revanced: ReturnYouTubeDislike: UI thread paused for: 1221ms waiting for vote fetch to complete
revanced: ReturnYouTubeDislike: UI thread paused for: 661ms waiting for vote fetch to complete
revanced: ReturnYouTubeDislike: UI thread paused for: 61ms waiting for vote fetch to complete
```

With patch.  Loading same 20 random videos:

```
revanced: ReturnYouTubeDislike: UI thread paused for: 762ms waiting for vote fetch to complete
revanced: ReturnYouTubeDislike: UI thread paused for: 159ms waiting for vote fetch to complete

```

2022-12-12 20:52 UTC, oSumAtrIX commented
Unsure if there is any improvement, both benchmarks show similar results.

2022-12-12 20:53 UTC, LisoUseInAIKyrios commented
without the patch, the UI waited 4 out of 20 times.

With the patch, it waited 2 out of 20 times.

2022-12-12 20:56 UTC, oSumAtrIX commented
Oh I see, i thought these were samples taken out of the 20.

2022-12-12 21:03 UTC, oSumAtrIX requested changes

2022-12-12 21:03 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
> +            recordTimeUISpentWaitingForNetworkCall(fetchStartTime);
A try-catch-finally block can be used in order to call `recordTimeUISpentWaitingForNetworkCall` before return without using duplicate code.

2022-12-16 14:25 UTC, LisoUseInAIKyrios commented
I added logging to the API network calls, and added user viewable statistics if debugging is enabled:
https://freeimage.host/i/HoDNhKB

Also added a Toast if a connection times out, or if a rate limit is encountered.

2022-12-18 22:47 UTC, oSumAtrIX approved these changes

2022-12-18 22:47 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
> +    // Must be volatile, since this is read/wright from different threads
```suggestion
    // Must be volatile, since this is read/write from different threads
```

2022-12-21 21:19 UTC, merged

2022-12-21 21:19 UTC, oSumAtrIX commented
Thanks!