feat: hide breaking news
revanced/revanced-integrations pull request #258
Opened 2022-12-28 17:26 UTC by 0xrxL

2022-12-28 17:44 UTC, oSumAtrIX requested changes

2022-12-28 17:44 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/HideBrekingNewsShelfPatch.java
> +public class HideBrekingNewsShelfPatch {
Misspelled "Breaking" here.

2022-12-28 17:44 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
> +    HIDE_BREAKING_NEWS_SHELF("revanced_hide_hide_breaking_news_shelf", false, ReturnType.BOOLEAN, true),
Duplicate settings name "hide_hide".

2022-12-29 02:02 UTC, oSumAtrIX requested changes

2022-12-29 02:02 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
> +    HIDE_BREAKING_NEWS_SHELF("revanced_hide_breaking_news_shelf", false, ReturnType.BOOLEAN, true),
```suggestion
    HIDE_BREAKING_NEWS_SHELF("revanced_hide_breaking_news_shelf", true, ReturnType.BOOLEAN, true),
```

2022-12-29 02:30 UTC, 0xrxL commented
Ok, now it's all ready. I mistakenly omitted some changes.

2022-12-29 16:40 UTC, oSumAtrIX approved these changes

2022-12-29 16:42 UTC, merged