feat(youtube): sponsorblock improvements
revanced/revanced-integrations pull request #308
Opened 2023-01-28 22:05 UTC by LisoUseInAIKyrios

integration changes for: https://github.com/revanced/revanced-patches/pull/1557

2023-01-28 23:18 UTC, oSumAtrIX commented
> Or maybe the debug toast setting should be changed to apply only to connection errors (and then a toast is always shown for all other errors).

How about following some OOP pattern for logging? Provide an interface that classes can implement and provide custom logging capabilities such as SponsorBlock only logging connection errors.

2023-01-28 23:54 UTC, oSumAtrIX commented
That would conflict with OOP principles. `logNetworkError` is something which should only be known to RYD and SponsorBlock, not globally available for other classes.

2023-01-29 00:06 UTC, oSumAtrIX commented
That would work as a temporary fix, it's not ideally implemented though, but will suffice for now.

2023-01-30 18:36 UTC, oSumAtrIX commented
Is this PR ready? The changes to the patches are marked as a draft.

2023-02-01 20:38 UTC, oSumAtrIX requested changes
Looks quite good & works locally.

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
> +            LogHelper.printDebug(() -> "current video length: " + length);
```suggestion
            LogHelper.printDebug(() -> "Current video length: " + length);
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
> +        LogHelper.printDebug(() -> "current video id: " + videoId);
```suggestion
        LogHelper.printDebug(() -> "Current video id: " + videoId);
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
> +            LogHelper.printDebug(() -> "current video time: " + time);
```suggestion
            LogHelper.printDebug(() -> "Current video time: " + time);
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
> +        ReVancedUtils.verifyOnMainThread();
Should this exception be raised to the caller?

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
> +                    defaultValue = SharedPrefHelper.getInt(setting.sharedPref, path, (Integer) defaultValue);
Why are objects used here instead of the primitives?

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/shared/PlayerType.kt
> +        @JvmStatic
Why is this annotated with `JvmStatic`?

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SponsorBlockView.java
> +        }
Is this logic necessary? The Android api already checks if the visibility has changed:

```java
    void setFlags(int flags, int mask) {
        // ....

        int old = mViewFlags;
        mViewFlags = (mViewFlags & ~mask) | (flags & mask);

        int changed = mViewFlags ^ old;
        if (changed == 0) {
            return;
        }
        
        // ....
}
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
> +        ReVancedUtils.verifyOffMainThread();
If this throws, this would crash the app, is this expected?

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
>          }
```suggestion
                LogHelper.printDebug(() -> "No segments found for video: " + videoId);
            } else {
                LogHelper.printException(() -> "getSegments failed with response code: " + responseCode);
                connection.disconnect(); // something went wrong, might as well disconnect
            }
        } catch (IOException ex) {
            LogHelper.printException(() -> "Failed to get segments", ex, str("sponsorblock_connection_timeout"));
        } catch (Exception ex) {
            LogHelper.printException(() -> "Failed to get segments", ex);
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
>          }
```suggestion
                LogHelper.printDebug(() -> "Successfully sent view count for segment: " + segment.UUID);
            } else {
                LogHelper.printDebug(() -> "Failed to sent view count for segment: " + segment.UUID
                        + " responseCode: " + responseCode); // debug level, no toast is shown
            }
        } catch (IOException ex) {
            LogHelper.printDebug(() -> "Could not send view count: " + ex); // do not show a toast
        } catch (Exception ex) {
            LogHelper.printException(() -> "Failed to send view count request", ex); // should never happen
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
>          try {
```suggestion
     * Injection point.
     * Updates SponsorBlock every 1000ms.
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
> +     */
```suggestion
     * Injection point.
     * Initializes SponsorBlock when the video player starts playing a new video.
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
> +                                // clear the field, so if user rewinds then timer can again be set for the same segment
```suggestion
                        LogHelper.printDebug(() -> "Scheduling skipping segment automatically");
                        nextSegmentToAutoSkip = segment;
                        ReVancedUtils.runOnMainThreadDelayed(() -> {
                            if (nextSegmentToAutoSkip != segment) {
                                LogHelper.printDebug(() -> "Ignoring stale scheduled skip: " + segment);
                            } else {
                                LogHelper.printDebug(() -> "Running scheduled skip");
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
> +                LogHelper.printDebug(() -> "clearing scheduled autoskip");
```suggestion
                LogHelper.printDebug(() -> "Clearing scheduled autoskip");
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
> +     * Patch injection point
```suggestion
     * Injection point.
```

2023-02-01 20:38 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/ShieldButton.java
>      private static int getInteger(String name) {
This belongs to `ReVancedUtils`. Theres other classes which require it as well.

2023-02-01 20:47 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
> +                    defaultValue = SharedPrefHelper.getInt(setting.sharedPref, path, (Integer) defaultValue);
Do primitives not implicitly work and shouldn't `SharedPrefHelper` methods use primitive types?

2023-02-01 20:50 UTC, oSumAtrIX commented on app/src/main/java/app/revanced/integrations/sponsorblock/ShieldButton.java
>      private static int getInteger(String name) {
Yes, there are couple of other methods which have their own `getInteger` method.

2023-02-04 13:38 UTC, oSumAtrIX commented
The PR is quite big; I will need some time to review it properly, bear with me; thanks for the contribution!

2023-02-08 04:11 UTC, Indranil012 commented
only "Skip" is good

2023-02-08 05:25 UTC, oSumAtrIX commented
I'd say, add an option to chose either, the one with more text might be easier to aim.

2023-02-10 18:28 UTC, oSumAtrIX commented
I'll test as well.

2023-02-18 23:06 UTC, oSumAtrIX requested changes
Seems like something went wrong and made some unwanted changes appear in this PR. Please rebase on top of/merge branch dev.

2023-02-18 23:10 UTC, oSumAtrIX commented
You are private on GitHub and I do not want to discuss something offtopic in this PR, can you reach out to me at osumatrix@revanced.app?

2023-04-02 14:10 UTC, merged

2023-04-02 18:56 UTC, oSumAtrIX commented
A suggestion for the future would be to use better commit message descriptions.

- Use a scope if the changes are related to a patch. This allows us to quickly understand, what the commit changed. Example: `fix(youtube/sponsorblock)`
- Stay in the present tense. Once the changelog is generated, it is easier to read that way. Example: `refactor: simplify code blocks`
- Use short sentences. This is good to stay consistent in how your commit message descriptions are read. Example: `feat: introduce new patch option`

For this PR, instead of `fix: sponsorblock improvements` say `refactor(youtube/sponsorblock): improve overall code quality`. Note that a **scope**, **present tense**, and **a short sentence** have been used. Also, this PR does not introduce any feature but rather a refactor. For that reason the commit type `refactor` is used.

Thanks for the huge effort on this PR!